name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Update Gradle wrapper (if needed)
      run: ./gradlew wrapper --gradle-version 7.0 --distribution-type=bin

    - name: Build with Gradle
      run: ./gradlew build

    - name: Debug build output
      run: ls -R build/libs

    - name: Set version tag
      run: |
        # Fetch tags from the repository
        git fetch --tags
        
        # Check if there are any tags, fallback to v1 if none
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1")

        # Extract the numeric part of the version tag
        VERSION_NUMBER=$(echo $VERSION | sed 's/v//g')  # Remove 'v' if present

        # Increment the version number by 1
        NEW_VERSION=$((VERSION_NUMBER + 1))

        # Set the new version tag
        VERSION_TAG="app-java-v$NEW_VERSION"

        # Save the new version tag to the environment variable
        echo "VERSION=$VERSION_TAG" >> $GITHUB_ENV
        echo "New Version Tag: $VERSION_TAG" # Debugging step to verify
        
      id: version

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: jeraldinnemg/java-app
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: ${{ env.VERSION }} 