name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Update Gradle wrapper (if needed)
      run: ./gradlew wrapper --gradle-version 7.0 --distribution-type=bin

    - name: Build with Gradle
      run: ./gradlew build

    - name: Debug build output
      run: ls -R build/libs

    # Generate versioned tag (using git tag or commit count)
    - name: Generate version tag
      id: version
      run: |
        # Check if there are any tags. If not, default to v0
        if git tag | wc -l > /dev/null; then
          # If there are tags, get the latest one and increment it
          VERSION=$(git describe --tags --abbrev=0)
          VERSION_NUMBER=$(echo $VERSION | sed 's/v//g')  # Remove 'v' if present
          NEW_VERSION=$((VERSION_NUMBER + 1)) # Increment version by 1
        else
          # If no tags exist, tag will start at v1
          NEW_VERSION=1
        fi
        echo "VERSION=app-java-v$NEW_VERSION" >> $GITHUB_ENV

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: jeraldinnemg/java-app
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}